name: dbus_secrets
description: A Dart package for managing secrets using D-Bus.
version: 0.0.1
repository: https://github.com/akshaybabloo/dbus_secrets

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  dbus: ^0.7.11

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
